import { Preahvihear, Plus_Jakarta_Sans, Poppins } from "next/font/google";
import "./globals.css";

const preahvihear = Preahvihear({
  weight: "400",
  variable: "--font-preahvihear",
  subsets: ["latin"],
});

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], 
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${preahvihear.variable} ${plusJakartaSans.variable} ${poppins.variable} font-preahvihear bg-[#11071F] antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
